name: CI

on:
  pull_request:

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - name: 'Install Node'
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - uses: pnpm/action-setup@v2
      name: Install pnpm
      with:
        version: 8
        run_install: true
    - name: Run ESLint
      run: pnpm run lint
  test:
    name: Test Code Base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - name: 'Install Node'
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Install xsel  
      run: sudo apt-get install -y xsel
    - uses: pnpm/action-setup@v2
      name: Install pnpm
      with:
        version: 8
        run_install: true
    - name: 'Test'
      run: pnpm run turbo:coverage
    - name: 'Report Core Coverage'
      if: always() # Also generate the report if tests are failing
      uses:  davelosert/vitest-coverage-report-action@v1
      with:
        json-summary-path: './coverage/coverage-summary.json'
        json-final-path: './coverage/coverage-final.json'
        vite-config-path: './configs/vitest/vitest.config.ts'
    - name: 'Report CLI Coverage'
      if: always() # Also generate the report if tests are failing
      uses:  davelosert/vitest-coverage-report-action@v1
      with:
        json-summary-path: './packages/cli/coverage/coverage-summary.json'
        json-final-path: './packages/cli/coverage/coverage-final.json'
        vite-config-path: './packages/cli/vitest.config.ts'
  design-request:
    name: Test Design Request Creation
    runs-on: ubuntu-latest
    environment:
      name: dev
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: 'Install Node'
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - uses: pnpm/action-setup@v2
      name: Install pnpm
      with:
        version: 8
        run_install: false
    - name: 'Install Deps'
      run: cd packages/cli && pnpm install && pnpm run setup:dev
    - name: 'Setup CLI'
      run: cd packages/cli/dist && node index.mjs config --api-host ${{vars.API_HOST}} --ws-host ${{vars.WEBSOCKET_HOST}} --api-key ${{secrets.API_KEY}} --user-id GITHUB-ACTIONS
    - name: 'Test'
      run: cd packages/cli/dist && node index.mjs mb-client design-request new --title $(date +'%Y-%m-%d') --subtitle ${GITHUB_REF##*/} --occasion baby --style 6117 --book-size 8x8 --cover-type sc --page-type sp --image-density low --image-filtering-level best --embellishment-level lots --text-sticker-level few --image-set 00-nice-and-rome
